source 'https://rubygems.org'

gem 'rails', '3.2.8'
gem 'sqlite3'
gem 'jquery-rails'
gem 'rabl'
gem 'rspec'
gem 'factory_girl_rails'

group :assets do
    gem 'sass-rails', '~> 3.2.3'
    gem 'coffee-rails', '~> 3.2.1'
    gem 'uglifier', '>= 1.0.3'
    gem 'twitter-bootstrap-rails', '~> 2.1.3'
    gem 'rails-backbone'
    gem 'handlebars_assets'
end

group :test, :development do
    gem "phantomjs"
    gem 'listen'
    gem "rspec-rails"
    gem 'guard-rspec'
    gem 'fuubar'
    gem 'jasminerice'
    gem 'guard-jasmine'
    gem 'jasmine-jquery-rails'
    gem 'sinon-rails'
end

group :test do
    gem 'rake'
    gem 'rest-client'
    gem 'capybara'
    gem 'capybara-webkit'
    gem 'capybara-screenshot'
    gem 'cucumber'
    gem 'cucumber-rails'
    gem 'database_cleaner'
end


